### ISSUE TITLE
Security Issue/Update: Roles

### ISSUE THREAD

**Issue by villam98** [villam98/dusty#4]
Need to update the **roles** according to the new **roles**.

**Changes** need to do on roles: 
- src/commands/enlist.js - need to **add** role checking.
- src/commands/lint.js - need to **add** role checking.
- src/commands/revoke.js - need to **add** role checking.
- src/commands/reboot.js - need to **update** role checking parameters
- src/commands/xp.js - need to **update** role checking parameters
- src/constants/ranks.js - will be needed **later**.

**Comment by bele321** [comment]
done!
